---
# Playbook to deploy Ghost and its components
# TO DO

#Criar PV
- name: Create PV
  hosts: localhost
  gather_facts: true
  roles:
    - create_pv

#- name: mysql Install
#  hosts: localhost
#  gather_facts: true
#  roles: 
#    - mysql_install
#
#- name: ghost Install
#  hosts: localhost
#  gather_facts: true
#  roles:
#    - ghost_install