---
- name: Create Prometheus
  hosts: localhost
  gather_facts: true
  roles: 
    - create_prometheus

- name: Ops Agents
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Ops Agents
      command: ansible-playbook -i inventory/nodes.inv ops-agent.yml
    
    - name: Clear Nodes
      ansible.builtin.file:
        path: inventory/nodes.py
        state: absent

- name: Create Mysql
  hosts: localhost
  gather_facts: true
  roles:
    - create_mysql

- name: Create Ghost
  hosts: localhost
  gather_facts: true
  roles:
    - create_ghost

- name: Add admin
  hosts: localhost
  gather_facts: true
  roles:
    - role: add_admin
      when: previous_install == false