---
# Playbook to deploy Ghost and its components

- name: Create Mysql
  hosts: localhost
  gather_facts: true
  roles:
    - create_mysql

- name: Create Ghost
  hosts: localhost
  gather_facts: true
  roles:
    - create_ghost

- name: Add admin
  hosts: localhost
  gather_facts: true
  roles:
    - add_admin