---

- name: Deploy Ghost Service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ ghost_service_name }}"
        namespace: default
        labels:
          app: ghost
          tier: app
      spec:
        type: LoadBalancer
        selector:
          app: ghost
        ports:
          - targetPort: "{{ ghost_internal_port }}" 
            port: "{{ ghost_port }}" 

- name: Wait until Service IP
  shell: bash ./inventory/verify_ip.sh {{ ghost_service_name }}
  register: command_output

- name: Get Ghost IP
  set_fact:
    ghost_ip: "{{ command_output.stdout }}"

- name: Save Ghost IP
  ansible.builtin.lineinfile:
    path: ./inventory/gcp.yml
    regexp: '  ghost_ip:\s*'
    line: '  ghost_ip: {{ ghost_ip }}'

- name: Deploy Ghost
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Deployment
      metadata:
        name: "{{ ghost_deployment_name }}"
        namespace: default
        labels:
          app: ghost
          tier: app 
      spec:
        selector:
          matchLabels:
            app: ghost
        template:
          metadata:
            labels:
              app: ghost
              tier: app
          spec:
            containers:
            - name: ghost
              image: ghost:5.14.1
              env:
              - name: url
                value: "http://{{ ghost_ip }}:{{ ghost_port }}"
              - name: database__client
                value: mysql
              - name: database__connection__host
                value: "{{ mysql_service_name }}"
              - name: database__connection__port
                value: '"{{ mysql_port }}"'
              - name: database__connection__user
                value: "{{ mysql_database_user }}"
              - name: database__connection__password
                value: "{{ mysql_database_password }}"
              - name: database__connection__database
                value: "{{ mysql_database_name }}"
              - name: mail__transport
                value: "SMTP"
              - name: mail__options__service
                value: "Mailgun"
              - name: mail__options__host
                value: "smtp.mailgun.org"
              - name: mail___options__port
                vaule: 587
              - name: mail__options__secure
                value: "true"
              - name: mail__options__auth__user
                value: "{{ ghost_mail_user }}"
              - name: mail__options__auth__pass
                value: "{{ ghost_mail_pass }}"
              ports:
              - containerPort: "{{ ghost_internal_port }}"

- name: Get Ghost Pods
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    label_selectors:
      - app = ghost
    namespace: default
  register: pods_info
  until: pods_info.resources[0].status.phase == "Running"
  delay: 60
  retries: 10