---

#- name: Create Docker Image
#  become: yes
#  community.docker.docker_image:
#    name: ghostim:latest
#    build:
#      path: ./inventory/
#    source: build

- name: Deploy Ghost
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Deployment
      metadata:
        name: "{{ ghost_deployment_name }}"
        namespace: default
        labels:
          app: ghost
          tier: app 
      spec:
        selector:
          matchLabels:
            app: ghost
        template:
          metadata:
            labels:
              app: ghost
              tier: app
          spec:
            containers:
            - name: ghost
              image: ghost:5.14.1
              env:
              - name: url
                value: http://{{ ghost_ip }}:{{ ghost_port }}
              - name: database
                value: mysql
              - name: database__connection__host
                value: "{{ mysql_service_name }}"
              - name: database__connection__user
                value: "{{ mysql_database_user }}"
              - name: database__connection__password
                value: "{{ mysql_database_password }}"
              - name: database__connection__database
                value: "{{ mysql_database_name }}"
              - name: NODE_ENV
                value: development
              ports:
              - containerPort: "{{ ghost_internal_port }}"

- name: Deploy Ghost Service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ ghost_service_name }}"
        namespace: default
        labels:
          app: ghost
          tier: app
      spec:
        type: LoadBalancer
        selector:
          app: ghost
        loadBalancerIP : "{{ ghost_ip }}"
        ports:
          - targetPort: "{{ ghost_internal_port }}" # port that containers are listening on 
            port: "{{ ghost_port }}" # port number exposed internally in the cluster